app_api:
  build: ./api
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  environment:
    - RAILS_ENV=development
  links:
    - postgres
  command:
    # - bundle install
    # - bundle exec rails s -b '0.0.0.0'
postgres:
  image: postgres:9.4
  restart: always
  ports:
    - "5432"
